/* kvraft_server_config.h

 Generated by phxrpc_pb2server from kvraft.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class KVRaftServerConfig {
  public:
    KVRaftServerConfig();

    virtual ~KVRaftServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

  private:
    phxrpc::HshaServerConfig ep_server_config_;
};

