/* kvraft_service_impl.cpp

 Generated by phxrpc_pb2service from kvraft.proto

*/

#include "kvraft_service_impl.h"

#include "phxrpc/file.h"

#include "kvraft_server_config.h"
#include "kvraft.pb.h"
#include "kvserver.h"


using namespace std;


KVRaftServiceImpl::KVRaftServiceImpl(ServiceArgs_t &app_args,
        phxrpc::UThreadEpollScheduler *const worker_uthread_scheduler)
        : args_(app_args), worker_uthread_scheduler_(worker_uthread_scheduler) {
}

KVRaftServiceImpl::~KVRaftServiceImpl() {
}

int KVRaftServiceImpl::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int KVRaftServiceImpl::RequestVote(const kvraft::RequestVoteArgs &req, kvraft::RequestVoteReply *resp) {
    args_.server->RequestVote(req,resp);
    return -1;
}

int KVRaftServiceImpl::AppendEntries(const kvraft::AppendEntriesArgs &req, kvraft::AppendEntriesReply *resp) {
	args_.server->AppendEntries(req,resp);
	return -1;
}

int KVRaftServiceImpl::Command(const kvraft::KVArgs &req, kvraft::KVReply *resp) {
	args_.server->Command(req,resp,worker_uthread_scheduler_);
    return -1;
}

