/* kvraft_client_uthread.h

 Generated by phxrpc_pb2client from kvraft.proto

*/

#pragma once

#include "kvraft.pb.h"
#include "phxrpc/network.h"
#include "phxrpc/rpc.h"

class KVRaftClientUThread {
   public:
    static bool Init(const char *config_file);

    static const char *GetPackageName();

    KVRaftClientUThread(phxrpc::UThreadEpollScheduler *uthread_scheduler);
    virtual ~KVRaftClientUThread();

    int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int RequestVote(const kvraft::RequestVoteArgs &req, kvraft::RequestVoteReply *resp, int index);
    int AppendEntries(const kvraft::AppendEntriesArgs &req, kvraft::AppendEntriesReply *resp,
                      int index);
    int Command(const kvraft::KVArgs &req, kvraft::KVReply *resp);

   private:
    phxrpc::UThreadEpollScheduler *uthread_scheduler_;
};
