/* kvraft_server_config.cpp

 Generated by phxrpc_pb2server from kvraft.proto

*/

#include "kvraft_server_config.h"

#include "kvraft.pb.h"


KVRaftServerConfig::KVRaftServerConfig() {
}

KVRaftServerConfig::~KVRaftServerConfig() {
}

bool KVRaftServerConfig::Read(const char *config_file) {
    bool ret{ep_server_config_.Read(config_file)};

    if (0 == strlen(ep_server_config_.GetPackageName())) {
        ep_server_config_.SetPackageName(
                kvraft::RequestVoteArgs::default_instance().GetDescriptor()->file()->package().c_str());
    }

    return ret;
}

phxrpc::HshaServerConfig &KVRaftServerConfig::GetHshaServerConfig() {
    return ep_server_config_;
}

