# Makefile
#
# Generated by phxrpc_pb2server from kvraft.proto
#
#

include /home/qyj/code/phxrpc/phxrpc.mk

LDFLAGS := -L$(PHXRPC_ROOT)/lib -lphxrpc $(LDFLAGS)

# choose to use boost for network
#LDFLAGS := $(PLUGIN_BOOST_LDFLAGS) $(LDFLAGS)

SVR_OBJS = kvraft.pb.o \
		kvraft_service_impl.o \
		phxrpc_kvraft_service.o \
		phxrpc_kvraft_dispatcher.o \
		kvraft_server_config.o \
		kvraft_main.o

CLI_OBJS = kvraft.pb.o \
		kvraft_client.o \
		kvraft_client_uthread.o \
		phxrpc_kvraft_stub.o

TARGETS = libkvraft_client.a kvraft_main kvraft_tool_main

all: $(TARGETS)

kvraft_main: $(SVR_OBJS)
	$(LINKER) $^ $(LDFLAGS) -o $@

libkvraft_client.a: $(CLI_OBJS)
	$(AR) $@ $^

kvraft_tool_main: phxrpc_kvraft_tool.o kvraft_tool_impl.o kvraft_tool_main.o
	$(LINKER) $^ -L. -lkvraft_client $(LDFLAGS) -o $@

########## message ##########

kvraft.pb.cc: kvraft.pb.h

kvraft.pb.h: kvraft.proto
	$(PROTOBUF_ROOT)/bin/protoc -I$(PROTOBUF_ROOT)/include --cpp_out=. -I$(PHXRPC_ROOT) -I. $^

########## client ##########

phxrpc_kvraft_stub.cpp: phxrpc_kvraft_stub.h
phxrpc_kvraft_stub.o: phxrpc_kvraft_stub.h
kvraft_client.cpp: phxrpc_kvraft_stub.h
kvraft_client.o: phxrpc_kvraft_stub.h
kvraft_client_uthread.cpp: phxrpc_kvraft_stub.h
kvraft_client_uthread.o: phxrpc_kvraft_stub.h

phxrpc_kvraft_stub.h: kvraft.proto
	$(PHXRPC_ROOT)/codegen/phxrpc_pb2client $(PBFLAGS) -f $^ -d . -u

########## service ##########

phxrpc_kvraft_service.cpp: phxrpc_kvraft_service.h
phxrpc_kvraft_service.o: phxrpc_kvraft_service.h
kvraft_service_impl.cpp: phxrpc_kvraft_service.h
kvraft_service_impl.o: phxrpc_kvraft_service.h
phxrpc_kvraft_dispatcher.cpp: phxrpc_kvraft_service.h
phxrpc_kvraft_dispatcher.o: phxrpc_kvraft_service.h

phxrpc_kvraft_service.h: kvraft.proto
	$(PHXRPC_ROOT)/codegen/phxrpc_pb2service $(PBFLAGS) -f $^ -d . -u

########## tool ##########

phxrpc_kvraft_tool.cpp: phxrpc_kvraft_tool.h
phxrpc_kvraft_tool.o: phxrpc_kvraft_tool.h
kvraft_tool_impl.cpp: phxrpc_kvraft_tool.h
kvraft_tool_impl.o: phxrpc_kvraft_tool.h
kvraft_tool_main.cpp: phxrpc_kvraft_tool.h
kvraft_tool_main.o: phxrpc_kvraft_tool.h

phxrpc_kvraft_tool.h: kvraft.proto
	$(PHXRPC_ROOT)/codegen/phxrpc_pb2tool $(PBFLAGS) -f $^ -d .

clean:
	@($(RM) $(TARGETS))
	@($(RM) *.o)
	@($(RM) phxrpc_*)
	@($(RM) *.pb.*)

