/* phxrpc_kvraft_stub.cpp

 Generated by phxrpc_pb2client from kvraft.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_kvraft_stub.h"

#include "phxrpc/http.h"
#include "phxrpc/network.h"
#include "phxrpc/rpc.h"


KVRaftStub::KVRaftStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
        phxrpc::BaseMessageHandlerFactory &msg_handler_factory)
        : socket_(socket), client_monitor_(client_monitor),
          msg_handler_factory_(msg_handler_factory) {
}

KVRaftStub::~KVRaftStub() {
}

void KVRaftStub::set_keep_alive(const bool keep_alive) {
    keep_alive_ = keep_alive;
}

int KVRaftStub::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/kvraft/PHXEcho", -1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int KVRaftStub::RequestVote(const kvraft::RequestVoteArgs &req, kvraft::RequestVoteReply *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/kvraft/RequestVote", -1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int KVRaftStub::AppendEntries(const kvraft::AppendEntriesArgs &req, kvraft::AppendEntriesReply *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/kvraft/AppendEntries", -1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

