/* phxrpc_kvraft_tool.cpp

 Generated by phxrpc_pb2tool from kvraft.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_kvraft_tool.h"

#include "phxrpc/file.h"

#include "kvraft_client.h"


using namespace phxrpc;


KVRaftTool::KVRaftTool() {
}

KVRaftTool::~KVRaftTool() {
}

int KVRaftTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int KVRaftTool::RequestVote(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** RequestVote unimplement ***\n");

    return -1;
}

int KVRaftTool::AppendEntries(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** AppendEntries unimplement ***\n");

    return -1;
}

