/* phxrpc_kvraft_service.cpp

 Generated by phxrpc_pb2service from kvraft.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_kvraft_service.h"

#include "kvraft.pb.h"
#include "phxrpc/file.h"


KVRaftService::KVRaftService() {
}

KVRaftService::~KVRaftService() {
}

int KVRaftService::PHXEcho(const google::protobuf::StringValue &/* req */, google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int KVRaftService::RequestVote(const kvraft::RequestVoteArgs &/* req */, kvraft::RequestVoteReply */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: RequestVote unimplemented");
    return -1;
}

int KVRaftService::AppendEntries(const kvraft::AppendEntriesArgs &/* req */, kvraft::AppendEntriesReply */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: AppendEntries unimplemented");
    return -1;
}

int KVRaftService::Command(const kvraft::KVArgs &/* req */, kvraft::KVReply */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Command unimplemented");
    return -1;
}

