/* phxrpc_kvraft_dispatcher.h

 Generated by phxrpc_pb2service from kvraft.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/rpc.h"


class KVRaftService;

class KVRaftDispatcher {
  public:
    static const phxrpc::BaseDispatcher<KVRaftDispatcher>::URIFuncMap &GetURIFuncMap();

    KVRaftDispatcher(KVRaftService &service, phxrpc::DispatcherArgs_t *dispatcher_args);

    virtual ~KVRaftDispatcher();

    int PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int RequestVote(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int AppendEntries(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Command(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);

  private:
    KVRaftService &service_;
    phxrpc::DispatcherArgs_t *dispatcher_args_;
};

