/* phxrpc_kvraft_stub.h

 Generated by phxrpc_pb2client from kvraft.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "kvraft.pb.h"


namespace phxrpc {


class BaseMessageHandlerFactory;
class BaseTcpStream;
class ClientMonitor;


}


class KVRaftStub {
  public:
    KVRaftStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
            phxrpc::BaseMessageHandlerFactory &msg_handler_factory);
    virtual ~KVRaftStub();

    void set_keep_alive(const bool keep_alive);

    int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int RequestVote(const kvraft::RequestVoteArgs &req, kvraft::RequestVoteReply *resp);
    int AppendEntries(const kvraft::AppendEntriesArgs &req, kvraft::AppendEntriesReply *resp);

  private:
    phxrpc::BaseTcpStream &socket_;
    phxrpc::ClientMonitor &client_monitor_;
    bool keep_alive_{false};
    phxrpc::BaseMessageHandlerFactory &msg_handler_factory_;
};

